name: Test deployment to LocalStack

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Start LocalStack
        uses: LocalStack/setup-localstack@v0.2.2
        with:
          image-tag: "latest"
          install-awslocal: "true"

      - name: Initialise and deploy terraform
        env:
          AWS_ENDPOINT_URL_CLOUDFRONT: "http://127.0.0.1:4566"
          AWS_ENDPOINT_URL_ROUTE_53: "http://127.0.0.1:4566"
          AWS_ENDPOINT_URL_ACM: "http://127.0.0.1:4566"
          AWS_ENDPOINT_URL_API_GATEWAY: "http://127.0.0.1:4566"
          AWS_ENDPOINT_URL_S3: "http://127.0.0.1:4566"
          AWS_ENDPOINT_URL_DYNAMODB: "http://127.0.0.1:4566"
          AWS_ENDPOINT_URL_IAM: "http://127.0.0.1:4566"
          TF_WORKSPACE: "dev"
          TF_VAR_branch: "feature/terraform"
        run: |
          terraform fmt -recursive
          terraform init -backend=false
          terraform plan \
            -var-file "tfvars/$TF_WORKSPACE.tfvars" \
            -var "branch=$TF_VAR_branch"
